"""
End-to-end demand forecasting pipeline.

Run order:
    ingest -> features -> temporal split -> train -> forecast ->
    hierarchical reconciliation -> coherence check -> evaluate ->
    financial translation -> publish artifacts

Usage:
    python run.py --data data --synthetic     # run on synthetic data (default if no M5)
    python run.py --data data                 # run on real M5 files in ./data
    python run.py --sample-frac 0.1           # subsample real M5 for speed

Outputs (written to reports/ and dashboard/):
    reports/accuracy.csv          per-series RMSSE
    reports/executive_brief.md    the business-facing summary
    dashboard/data.json           data for the published dashboard
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import pandas as pd

from src import data as data_mod
from src import evaluate, features, model, reconciliation, synthetic

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("run")

RECONCILE_LEVELS = ["total", "state_id", "store_id", "cat_id", "dept_id", "item_store"]


def main() -> None:
    ap = argparse.ArgumentParser(description="Hierarchical demand forecasting pipeline")
    ap.add_argument("--data", default="data", help="directory with M5 CSVs")
    ap.add_argument("--synthetic", action="store_true", help="generate synthetic data first")
    ap.add_argument("--sample-frac", type=float, default=None, help="subsample series fraction")
    ap.add_argument("--horizon", type=int, default=28, help="forecast horizon in days")
    args = ap.parse_args()

    data_dir = Path(args.data)

    # If the real files are absent, fall back to synthetic so the repo always runs.
    if args.synthetic or not (data_dir / data_mod.SALES_FILE).exists():
        logger.info("using synthetic M5 data")
        synthetic.generate(data_dir)

    # 1. ingest + validate
    m5 = data_mod.load_m5(data_dir, sample_frac=args.sample_frac)

    # 2. features
    feat = features.build_features(m5.sales_long, m5.calendar, m5.prices)
    feature_cols = [c for c in feat.columns if c.startswith(("lag_", "roll_", "te_", "price_"))]
    feature_cols += ["dow", "month", "is_weekend", "has_event", "snap"]
    feature_cols = [c for c in feature_cols if c in feat.columns]

    # 3. temporal split
    train, test = model.train_test_split_temporal(feat, horizon_days=args.horizon)

    # 4. train
    fm = model.ForecastModel().fit(train, feature_cols)

    # 5. forecast the held-out horizon
    test = test.copy()
    test["forecast"] = fm.predict(test)

    # 6. hierarchical reconciliation + coherence check
    id_cols = ["item_store", "item_id", "store_id", "dept_id", "cat_id", "state_id"]
    bottom = test[id_cols + ["date", "wm_yr_wk", "forecast"]].copy()
    reconciled = reconciliation.reconcile_bottom_up(bottom, RECONCILE_LEVELS, "forecast")
    coherent = reconciliation.check_coherence(reconciled, "forecast")
    if not coherent:
        raise RuntimeError("forecasts failed coherence check; not safe to publish")

    # 7. evaluate accuracy
    accuracy = evaluate.evaluate_series(test, train)
    Path("reports").mkdir(exist_ok=True)
    accuracy.to_csv("reports/accuracy.csv", index=False)

    # 8. financial translation
    fin = evaluate.financial_translation(test, m5.prices)
    summary = evaluate.executive_summary(fin)

    # 9. publish artifacts
    write_brief(summary, accuracy, reconciled)
    write_dashboard_data(summary, accuracy, reconciled, fin)
    logger.info("pipeline complete. mean RMSSE %.3f", accuracy["rmsse"].mean())


def write_brief(summary, accuracy, reconciled) -> None:
    """Write the business-facing executive brief."""
    lines = [
        "# Demand Forecast — Executive Brief",
        "",
        f"_Auto-generated by the forecasting pipeline. Horizon: "
        f"{summary['forecast_horizon_days']} days._",
        "",
        "## Headline",
        "",
        f"- **Expected units:** {summary['expected_units']:,}",
        f"- **Expected revenue:** ${summary['expected_revenue']:,.0f}",
        f"- **Forecast-error cost:** ${summary['forecast_error_cost']:,.0f} "
        f"({summary['error_cost_pct_of_revenue']}% of revenue)",
        f"- **Mean RMSSE:** {accuracy['rmsse'].mean():.3f} "
        f"(< 1.0 means better than a naive forecast)",
        "",
        "## What this means",
        "",
        "Forecasts are coherent across every planning level — store totals sum "
        "to category totals, which sum to the grand total — so store managers, "
        "category buyers, and finance plan against the same numbers. The "
        "error-cost figure prices the forecast's mistakes asymmetrically: a "
        "stockout costs the full margin lost, an overstock costs the capital "
        "tied up. That is the number to drive down, not raw accuracy alone.",
        "",
        "_The instruments behind turning these forecasts into pricing and "
        "assortment decisions are discussed in The Analytics System "
        "(theanalyticssystem.com)._",
    ]
    Path("reports/executive_brief.md").write_text("\n".join(lines))


def write_dashboard_data(summary, accuracy, reconciled, fin) -> None:
    """Write the JSON the dashboard reads."""
    Path("dashboard").mkdir(exist_ok=True)
    by_state = (
        reconciled["state_id"].groupby("state_id")["forecast"].sum().round().to_dict()
        if "state_id" in reconciled else {}
    )
    by_cat = (
        reconciled["cat_id"].groupby("cat_id")["forecast"].sum().round().to_dict()
        if "cat_id" in reconciled else {}
    )
    total_series = (
        reconciled["total"].assign(date=lambda d: d["date"].astype(str))
        [["date", "forecast"]].to_dict(orient="records")
    )
    payload = {
        "summary": summary,
        "mean_rmsse": round(float(accuracy["rmsse"].mean()), 3),
        "forecast_by_state": by_state,
        "forecast_by_category": by_cat,
        "total_daily": total_series,
    }
    Path("data.json").write_text(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
